Some logs and validation.

diff --git a/bin/aws-deploy b/bin/aws-deploy
--- a/bin/aws-deploy
+++ b/bin/aws-deploy
@@ -1,11 +1,37 @@
 #!/usr/bin/env bash
 
 PROJECT_NAME="$1"
-BRANCH_NAME="$2"
+if [[ "$PROJECT_NAME" == "" ]]; then
+    echo "Missing project name." >&2
+    echo "Command should be:" >&2
+    echo "\taws-deploy <project name> <branch name>" >&2
+    exit 1
+fi
 
+BRANCH_NAME="$2"
+if [[ "$BRANCH_NAME" == "" ]]; then
+    echo "Missing branch name." >&2
+    echo "Command should be:" >&2
+    echo "\taws-deploy <project name> <branch name>" >&2
+    exit 1
+fi
+
+POOLING_INTERVAL="$3"
+if [[ "$POOLING_INTERVAL" == "" ]]; then
+    POOLING_INTERVAL="2"
+fi
+if ! [[ $POOLING_INTERVAL =~ '^[0-9]+$' ]] ; then
+    POOLING_INTERVAL="2"
+fi
+
+echo
+echo "Start building $BRANCH_NAME to $PROJECT_NAME."
 BUILD_RESULT=`aws --region us-east-1 codebuild start-build --project-name "$PROJECT_NAME" --source-version "$BRANCH_NAME" | tr '\n' ' ' | tr '\t' ' '`
 BUILD_ID=`echo $BUILD_RESULT | sed -E 's/.*"id": "([^"]*)".*/\1/g'`
+echo "Build finished."
 
+echo
+echo "Start status pooling with an interval of $POOLING_INTERVAL seconds."
 BUILD_COMPLETE="false"
 while [[ "$BUILD_COMPLETE" != "true" ]]; do
 
@@ -13,10 +39,9 @@ while [[ "$BUILD_COMPLETE" != "true" ]]; do
     BUILD_COMPLETE=`echo $LIST_RESULT | sed -E 's/.*"buildComplete": ([a-z]*).*/\1/g'`
     BUILD_STATUS=`echo $LIST_RESULT | sed -E 's/.*"buildStatus": "([^"]*)".*/\1/g'`
     echo "Current status: $BUILD_STATUS"
-    sleep 2
+    sleep $POOLING_INTERVAL
 
 done
 
-echo
 echo
 echo "Finished with status: $BUILD_STATUS"
