Várias baguncinhas para ajustar os serviços no macOS e instalar o chunkwm.

diff --git a/bin/aws-deploy b/bin/aws-deploy
--- a/bin/aws-deploy
+++ b/bin/aws-deploy
@@ -2,17 +2,17 @@
 
 PROJECT_NAME="$1"
 if [[ "$PROJECT_NAME" == "" ]]; then
-    echo "Missing project name." >&2
-    echo "Command should be:" >&2
-    echo "\taws-deploy <project name> <branch name>" >&2
+    echo    "Missing project name." >&2
+    echo    "Command should be:" >&2
+    echo -e "\taws-deploy <project name> <branch name>" >&2
     exit 1
 fi
 
 BRANCH_NAME="$2"
 if [[ "$BRANCH_NAME" == "" ]]; then
-    echo "Missing branch name." >&2
-    echo "Command should be:" >&2
-    echo "\taws-deploy <project name> <branch name>" >&2
+    echo    "Missing branch name." >&2
+    echo    "Command should be:" >&2
+    echo -e "\taws-deploy <project name> <branch name>" >&2
     exit 1
 fi
 
